### PR TITLE
Made new lines optional in some places when parsing input

### PR DESCRIPTION
**Pull request by ghost**
Making new lines optional in these places is required for compatibility with output I've generated in TCPDF

### CODE REVIEW

**Comment by asika32764** [comment]
Thank you, could you provide some before and after comparison to help me test?

**Comment by ghost** [comment]
Sorry, I'd be hesitant to provide a full PDF as it could contain private data. I've manually decoded the stream and can paste a screenshot if that helps?

pdf_sample

Looking at this it might be better to change `BT[\n|\r]?` to `BT[\n|\r| ]` or similar. I'll update the PR.

Any thoughts?

**Comment by asika32764** [comment]
OK, since It's hard to test it by a real PDF, I'll accept this PR first.

Thank you for contribution.

**Comment by ghost** [comment]
Thank you, I appreciate it :)

**Pull request merged**
