### PR TITLE
Slight Modernisation

### PR DESCRIPTION
**Pull request by perk11**
I cleaned up what was a sore in the eye.

Last commit is a BC break, first 3 are not.

### CODE REVIEW

**Comment by asika32764** [comment]
Since there may be many projects using this library, I will suggest that we can mark `setFilename()` and `decodePDF()` to deprecated and create a new `decode()` method as main entry. That will keep the B/C.

Otherwise it will need a major release to break the interface.

What do you think?

**Comment by perk11** [comment]
What about the other methods, `convertQuotes()`, `showProgress()`, `setUnicode()`?
Removing this is a BC break too.

**Comment by asika32764** [comment]
Yes, I think we can mark all these methods as deprecated and wrap it in a single entry method, since this class still exists the properties and is stateful:

``` php
public decode (...) {
    return $this->setFilename(...)
        ->setUnicode(...)
        ...
        ->decodePDF();
}
```

Otherwise I must upgrade the version to 2.0 but you will not able to use this change instantly until I release 2.0 stable.

**Comment by perk11** [comment]
Did that, should be good to go now.

**Comment by perk11** [comment]
Did that, should be good to go now.

**Comment by asika32764** [comment]
Test ok :+1: 

Thank you

**Comment by asika32764** [comment]
New release https://github.com/asika32764/php-pdf-2-text/releases/tag/1.0.4

**Pull request merged**
